// Copyright Epic Games, Inc. All Rights Reserved.

#include "../NiagaraStatelessCommon.ush"

uint	DynamicMaterialParameters_ChannelMask;
FNiagaraStatelessBuiltDistributionType	DynamicMaterialParameters_Parameter0X;
FNiagaraStatelessBuiltDistributionType	DynamicMaterialParameters_Parameter0Y;
FNiagaraStatelessBuiltDistributionType	DynamicMaterialParameters_Parameter0Z;
FNiagaraStatelessBuiltDistributionType	DynamicMaterialParameters_Parameter0W;
FNiagaraStatelessBuiltDistributionType	DynamicMaterialParameters_Parameter1X;
FNiagaraStatelessBuiltDistributionType	DynamicMaterialParameters_Parameter1Y;
FNiagaraStatelessBuiltDistributionType	DynamicMaterialParameters_Parameter1Z;
FNiagaraStatelessBuiltDistributionType	DynamicMaterialParameters_Parameter1W;
FNiagaraStatelessBuiltDistributionType	DynamicMaterialParameters_Parameter2X;
FNiagaraStatelessBuiltDistributionType	DynamicMaterialParameters_Parameter2Y;
FNiagaraStatelessBuiltDistributionType	DynamicMaterialParameters_Parameter2Z;
FNiagaraStatelessBuiltDistributionType	DynamicMaterialParameters_Parameter2W;
FNiagaraStatelessBuiltDistributionType	DynamicMaterialParameters_Parameter3X;
FNiagaraStatelessBuiltDistributionType	DynamicMaterialParameters_Parameter3Y;
FNiagaraStatelessBuiltDistributionType	DynamicMaterialParameters_Parameter3Z;
FNiagaraStatelessBuiltDistributionType	DynamicMaterialParameters_Parameter3W;
	
void DynamicMaterialParameters_Simulate(inout FStatelessParticle Particle)
{
	Particle.DynamicMaterialParameter0 = 0.0f;
	Particle.DynamicMaterialParameter1 = 0.0f;
	Particle.DynamicMaterialParameter2 = 0.0f;
	Particle.DynamicMaterialParameter3 = 0.0f;

	if ((DynamicMaterialParameters_ChannelMask & 0x000f) != 0)
	{
		FStatelessDistributionSamplerFloat ParameterSampler[4];
		ParameterSampler[0].Init(0, DynamicMaterialParameters_Parameter0X);
		ParameterSampler[1].Init(1, DynamicMaterialParameters_Parameter0Y);
		ParameterSampler[2].Init(2, DynamicMaterialParameters_Parameter0Z);
		ParameterSampler[3].Init(3, DynamicMaterialParameters_Parameter0W);
		
		Particle.DynamicMaterialParameter0.x = (DynamicMaterialParameters_ChannelMask & 0x0001) != 0 ? ParameterSampler[0].GetValue(Particle.NormalizedAge) : 0.0f;
		Particle.DynamicMaterialParameter0.y = (DynamicMaterialParameters_ChannelMask & 0x0002) != 0 ? ParameterSampler[1].GetValue(Particle.NormalizedAge) : 0.0f;
		Particle.DynamicMaterialParameter0.z = (DynamicMaterialParameters_ChannelMask & 0x0004) != 0 ? ParameterSampler[2].GetValue(Particle.NormalizedAge) : 0.0f;
		Particle.DynamicMaterialParameter0.w = (DynamicMaterialParameters_ChannelMask & 0x0008) != 0 ? ParameterSampler[3].GetValue(Particle.NormalizedAge) : 0.0f;
	}

	if ((DynamicMaterialParameters_ChannelMask & 0x00f0) != 0)
	{
		FStatelessDistributionSamplerFloat ParameterSampler[4];
		ParameterSampler[0].Init(4, DynamicMaterialParameters_Parameter1X);
		ParameterSampler[1].Init(5, DynamicMaterialParameters_Parameter1Y);
		ParameterSampler[2].Init(6, DynamicMaterialParameters_Parameter1Z);
		ParameterSampler[3].Init(7, DynamicMaterialParameters_Parameter1W);
		
		Particle.DynamicMaterialParameter1.x = (DynamicMaterialParameters_ChannelMask & 0x0010) != 0 ? ParameterSampler[0].GetValue(Particle.NormalizedAge) : 0.0f;
		Particle.DynamicMaterialParameter1.y = (DynamicMaterialParameters_ChannelMask & 0x0020) != 0 ? ParameterSampler[1].GetValue(Particle.NormalizedAge) : 0.0f;
		Particle.DynamicMaterialParameter1.z = (DynamicMaterialParameters_ChannelMask & 0x0040) != 0 ? ParameterSampler[2].GetValue(Particle.NormalizedAge) : 0.0f;
		Particle.DynamicMaterialParameter1.w = (DynamicMaterialParameters_ChannelMask & 0x0080) != 0 ? ParameterSampler[3].GetValue(Particle.NormalizedAge) : 0.0f;
	}

	if ((DynamicMaterialParameters_ChannelMask & 0x0f00) != 0)
	{
		FStatelessDistributionSamplerFloat ParameterSampler[4];
		ParameterSampler[0].Init(8, DynamicMaterialParameters_Parameter2X);
		ParameterSampler[1].Init(9, DynamicMaterialParameters_Parameter2Y);
		ParameterSampler[2].Init(10, DynamicMaterialParameters_Parameter2Z);
		ParameterSampler[3].Init(11, DynamicMaterialParameters_Parameter2W);
		
		Particle.DynamicMaterialParameter2.x = (DynamicMaterialParameters_ChannelMask & 0x0100) != 0 ? ParameterSampler[0].GetValue(Particle.NormalizedAge) : 0.0f;
		Particle.DynamicMaterialParameter2.y = (DynamicMaterialParameters_ChannelMask & 0x0200) != 0 ? ParameterSampler[1].GetValue(Particle.NormalizedAge) : 0.0f;
		Particle.DynamicMaterialParameter2.z = (DynamicMaterialParameters_ChannelMask & 0x0400) != 0 ? ParameterSampler[2].GetValue(Particle.NormalizedAge) : 0.0f;
		Particle.DynamicMaterialParameter2.w = (DynamicMaterialParameters_ChannelMask & 0x0800) != 0 ? ParameterSampler[3].GetValue(Particle.NormalizedAge) : 0.0f;
	}

	if ((DynamicMaterialParameters_ChannelMask & 0xf000) != 0)
	{
		FStatelessDistributionSamplerFloat ParameterSampler[4];
		ParameterSampler[0].Init(12, DynamicMaterialParameters_Parameter3X);
		ParameterSampler[1].Init(13, DynamicMaterialParameters_Parameter3Y);
		ParameterSampler[2].Init(14, DynamicMaterialParameters_Parameter3Z);
		ParameterSampler[3].Init(15, DynamicMaterialParameters_Parameter3W);
		
		Particle.DynamicMaterialParameter3.x = (DynamicMaterialParameters_ChannelMask & 0x1000) != 0 ? ParameterSampler[0].GetValue(Particle.NormalizedAge) : 0.0f;
		Particle.DynamicMaterialParameter3.y = (DynamicMaterialParameters_ChannelMask & 0x2000) != 0 ? ParameterSampler[1].GetValue(Particle.NormalizedAge) : 0.0f;
		Particle.DynamicMaterialParameter3.z = (DynamicMaterialParameters_ChannelMask & 0x4000) != 0 ? ParameterSampler[2].GetValue(Particle.NormalizedAge) : 0.0f;
		Particle.DynamicMaterialParameter3.w = (DynamicMaterialParameters_ChannelMask & 0x8000) != 0 ? ParameterSampler[3].GetValue(Particle.NormalizedAge) : 0.0f;
	}
}
